---
title: "Project"
author: "Paul Sirena"
date: "11/2/2020"
output: html_document
---

```{r echo=FALSE}
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
```

```{r Data, echo=FALSE,warning=FALSE}
data <- read_csv("BAIS6060_ProjectData.csv",col_types=cols(player_name=col_factor(),events=col_factor(),
                                                           description=col_factor(),launch_speed=col_double()))
```

```{r IBB Data, echo=FALSE,warning=FALSE}
IBB <- cbind(c("Mookie Betts","Mike Yastrzemski","Fernando Tatis Jr.","Manny Machado","Freddie Freeman","Juan Soto"),
             c(1,2,1,4,7,12))
IBB <- as.data.frame(IBB)
names(IBB) <- c("player_name","IBB")
```


```{r Traditional Stats Function, echo=FALSE}
PlayerTraditionalStats <- function(player) {
  TraditionalStats <- data %>% filter(player_name==player) %>%
    summarize(player_name = player_name, 'PA' = sum(pitch_number==1) - 
                sum(outs_when_up==2 & (events=="pickoff_1b" | events=="pickoff_caught_stealing_2b" | 
                                         events=="caught_stealing_2b")), 
              'AB' = PA - sum(events=="walk") - sum(events=="hit_by_pitch") - sum(events=="sac_fly"),
              'H' = sum(events=="single" | events=="double" | events=="triple" | events=="home_run"), 
              '1B' = sum(events=="single"), '2B' = sum(events=="double"), '3B' = sum(events=="triple"), 'HR' = sum(events=="home_run"),
              'BB' = sum(events=="walk"), 'HR' = sum(events=="home_run"))
  
  TraditionalStats <- left_join(TraditionalStats,IBB,"player_name")
  
  TraditionalStats <- TraditionalStats %>%
    transmute('Player Name' = player_name, 'PA' = PA,'AB' = AB, 'H' = H, '1B' = `1B`, '2B' = `2B`, '3B' = `3B`, 'HR' = HR,
              'BB' = BB + as.numeric(IBB), 'IBB' = IBB, 
              'AVG' = round(H/AB, 3), 'OBP' = round((H+BB)/PA, 3), 'SLG' = round((`1B`+2*`2B`+3*`3B`+4*HR)/AB, 3),
              'OPS' = OBP+SLG)
  
  return(TraditionalStats[1,])
}
```

```{r Player Stats}
Freeman <- PlayerTraditionalStats("Freddie Freeman")
Betts <- PlayerTraditionalStats("Mookie Betts")
Machado <- PlayerTraditionalStats("Manny Machado")
Tatis <- PlayerTraditionalStats("Fernando Tatis Jr.")
Soto <- PlayerTraditionalStats("Juan Soto")
Yastrzemski <- PlayerTraditionalStats("Mike Yastrzemski")
```


```{r Exit Velocity Analysis}
ExitVelo <- data %>% group_by(player_name) %>% filter(description!="foul") %>%
  summarize('Average Exit Velo' = round(mean(launch_speed, na.rm=TRUE), 1), 
            'Hard Hit Rate' = round(sum(launch_speed >= 95, na.rm=TRUE) / sum(!is.na(launch_speed)) * 100, 1)) %>%
  arrange(desc(`Hard Hit Rate`))
names(ExitVelo)[1] <- "Player Name"
```

```{r Chasing Pitches}
data$InZone <- as.factor(ifelse((data$plate_z <= 3.5 & data$plate_z >= 1.5) &
                                  (data$plate_x >= -.833 & data$plate_x <= .833),1,0))
data$Swing <- as.factor(ifelse(data$description == "foul" | data$description == "hit_into_play" | data$description == "foul_tip" |
                                 data$description == "hit_into_play_no_out" | data$description == "swinging_strike" |
                                 data$description == "swinging_strike_blocked" | data$description == "foul_bunt" |
                                 data$description == "hit_into_play_score" | data$description == "missed_bunt", 1, 0))

SwingAnalysis <- data %>% group_by(player_name) %>%
  summarize('Chase %' = round(sum(InZone==0 & Swing==1)/sum(InZone==0)*100, 1),
            'In-Zone Swing %' = round(sum(InZone==1 & Swing==1)/sum(InZone==1)*100, 1)) %>% arrange(`Chase %`)
names(SwingAnalysis)[1] <- "Player Name"
```


